name: CD-Liara
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
      - name: Build Flutter Web
        run: flutter build web
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@3
          liara deploy --path=./build/web --app="hamidjalili-cv" --api-token="$LIARA_TOKEN" --detach
